# -*- coding: utf-8 -*-
"""SB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtgoGuucGdvbHb5rJWPvw0U1QAM1gc_c
"""

print('SampleBranch')